```{r}
setwd("C:/Users/zhaoi2/Desktop/project") 
source("./Supplemental/check_packages.R")
source("./Supplemental/custom_cormatrix.R")  # use to load correlation matrix function
check_packages(c("optimx","metafor","stringr","Hmisc","ggpubr","readxl","xlsx","sas7bdat","readstata13","gridExtra","RColorBrewer","sjPlot",
                 "grid","lme4","ggrepel","tidyr","networkD3","dplyr","ggplot2"))

# Name estrogens
estrogen_names = c("E1", "E2", "4OHE1", "4ME1","4ME2","2OHE1","3ME1" ,"2OHE2","2ME1","2ME2","16aE1","17epiE3","E3","16KE2","16epiE3") 
estrogen_names_long = c("Estrone (E1)", "Estradiol (E2)", "4-Hydroxyestrone (4OHE1)", "4-Methoxyestrone (4ME1)","4-Methoxyestradiol (4ME2)","2-Hydroxyestrone (2OHE1)","2-Hydroxyestrone-3-methyl ether (3ME1)" ,"2-Hydroxyestradiol (2OHE2)","2-Methoxyestrone (2ME1)","2-Methoxyestradiol (2ME2)","16a-Hydroxyestrone (16aE1)","17-Epiestriol (17epiE3)","Estriol (E3)","16-Ketoestradiol (16KE2)","16-Epiestriol (16epiE3)")
estrogen_names_long2 = c("Estrone", "Estradiol", "4-Hydroxyestrone", "4-Methoxyestrone","4-Methoxyestradiol","2-Hydroxyestrone","2-Hydroxyestrone-3-methyl ether" ,"2-Hydroxyestradiol","2-Methoxyestrone","2-Methoxyestradiol","16a-Hydroxyestrone","17-Epiestriol","Estriol","16-Ketoestradiol","16-Epiestriol")
estrogen_names_df = data.frame(Estrogen = estrogen_names, Nomenclature = estrogen_names_long2)
t.estrogen_names = paste0("t.",estrogen_names)

#load("./data/df_all.RDA")
```


Compare pairs
```{r}
max.batch = 9   # change to 16 when final

df.old = list()  # will store all batches into one list of multiple dataframes
for (i in 1:max.batch){  # reads in batches 1-4
  df.old[[i]] = as.data.frame(read_excel(paste0("./data/estrogen_old/Batch",as.character(i), ".xlsm"),na="NF",skip=2))    # reads in batches starting row 3, replacing NF with NA
  df.old[[i]]$batch.num = i   # makes a new column to identify batch
  df.old[[i]]$type="old"
  colnames(df.old[[i]])[1:4] = c("sample.id","customer.id","volume","injection")   # renames first 4 columns to standardize format
}
df.old[[8]] = df.old[[8]] %>% filter(!(customer.id %in% c("C_25","C_26","C_27","C_28")))
df.old = bind_rows(df.old)


df.new = list()  # will store all batches into one list of multiple dataframes
for (i in 1:max.batch){  # reads in batches 1-4
  df.new[[i]] = as.data.frame(read_excel(paste0("./data/estrogen_new/Batch_",as.character(i), "_rev2.xlsm"),na="NF",skip=2))    # reads in batches starting row 3, replacing NF with NA
  df.new[[i]]$batch.num = i   # makes a new column to identify batch
  df.new[[i]]$type="new"
  colnames(df.new[[i]])[1:4] = c("sample.id","customer.id","volume","injection")   # renames first 4 columns to standardize format
}
df.new[[8]] = df.new[[8]] %>% filter(!(customer.id %in% c("C_25","C_26","C_27","C_28")))
df.new = bind_rows(df.new) 

df.compare = bind_rows(df.old,df.new) %>% select(sample.id,customer.id,batch.num,type,estrogen_names)  %>%
           gather(Estrogen,Concentration,estrogen_names) %>%
  mutate(batch.type = factor(as.factor(paste0(type,batch.num)),levels = paste0(rep(c("old","new"),max.batch), sort(rep(seq(1,max.batch),2)))),
         Estrogen = factor(as.factor(Estrogen),levels = estrogen_names)) 
df.compare2 = bind_rows(df.old,df.new) %>% select(sample.id,customer.id,batch.num,type,estrogen_names) 


ggpaired(df.compare, x = "batch.type", y = "Concentration", id="customer.id",facet.by="Estrogen",color = "type", line.color = "gray", line.size = 0.4,palette = "jco",xlab = "") +
  scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels =scales::trans_format("log10", scales::math_format(10^.x)))+
  theme(legend.position="bottom")+
  ylab("Estrogen Concentration (pg) unstandardized")+
xlab("Batch Number")+
 scale_x_discrete(labels = as.character(sort(rep(seq(1,max.batch),2))))+
  facet_wrap(~ Estrogen, scales="free",ncol=5)+
       guides(color = guide_legend(reverse = TRUE))

```

Compare nf counts
```{r}
df.old2 = bind_rows(df.old) %>% gather(Estrogen,Concentration,estrogen_names) %>% select(customer.id,batch.num,Estrogen,Concentration) %>% rename(Old.Concentration = Concentration)

df.new2 = bind_rows(df.new) %>% gather(Estrogen,Concentration,estrogen_names) %>% select(customer.id,batch.num,Estrogen,Concentration) %>% rename(New.Concentration = Concentration)

df.nf = df.old2 %>% inner_join(df.new2) %>% filter(is.na(Old.Concentration)| is.na(New.Concentration) ) %>% filter(!(is.na(Old.Concentration)& is.na(New.Concentration))  ) %>% filter(customer.id != "0121") %>% arrange(batch.num) %>% mutate(Old.Concentration = round(Old.Concentration,2),New.Concentration = round(New.Concentration,2)   )

df.nf[is.na(df.nf)] = "NF"

sjPlot::tab_df(df.nf,show.rownames=FALSE)
```


Compare qcs
```{r}
qc.df = df.compare2 %>% filter((str_detect(customer.id, regex("control|Xia|C-|C_",ignore_case=TRUE)))) %>%
  filter(!(str_detect(customer.id, regex("Y",ignore_case=TRUE)))) %>%
  filter(batch.num !=8) %>%
  mutate(ID = rep(c("A","D","A","D", # batch 1
                    "B","B","D","D", # batch 2
                    "E","B","B","E", # batch 3
                    "D","E","E","D",  # batch 4
                    "E","E","B","B", # batch 5
                    "B","D","B","D", # batch 6
                    "A","A","B","B", # batch 7
                    "B","B","E","E"  # batch 9
                    ),2) ) %>%
  gather(Estrogen,Concentration,estrogen_names) %>%
  mutate(batch.num = factor(as.factor(batch.num),levels = as.character(seq(1:4))),type = as.factor(type),
         type.ID = paste0(type,"_",ID)
         ) 

qc.stats.old = as.data.frame(qc.df %>% filter(type=="old") %>% group_by(Estrogen) %>%
  summarize(s2_between_subject = VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num)))$ID[1] ,           # between subject variance
            s2_between_batch = VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num)))$batch.num[1] ,          # between batch variance
            s2_within_subject = (attr(VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num))), "sc"))^2 ,    # within subject variance
         #var.error =    (attr(VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num))   ), "sc"))^2,
          #  var.resid =   VarCorr(lmer(Concentration ~ 1+ (1|ID)))$ID[1],
            #cv = round(sqrt(var.resid)/mean(Concentration,na.rm=TRUE),2),
           # cv = round((sqrt(exp(var.error)-1)),2),
            #icc = round(var.resid/(var.resid+var.error),2)
            max = max(Concentration,na.rm=TRUE),
         icc.old = round(  s2_between_subject/(s2_between_subject+s2_within_subject+s2_between_batch), 4)  ,
          cv.old = round(sqrt(s2_within_subject + s2_between_batch)/mean(Concentration,na.rm=TRUE),4)))

qc.stats.new = as.data.frame(qc.df %>% filter(type=="new") %>% filter(Estrogen != '4OHE1') %>% group_by(Estrogen) %>%
  summarize(s2_between_subject = VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num)))$ID[1] ,           # between subject variance
            s2_between_batch = VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num)))$batch.num[1] ,          # between batch variance
            s2_within_subject = (attr(VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num))), "sc"))^2 ,    # within subject variance
         #var.error =    (attr(VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num))   ), "sc"))^2,
          #  var.resid =   VarCorr(lmer(Concentration ~ 1+ (1|ID)))$ID[1],
            #cv = round(sqrt(var.resid)/mean(Concentration,na.rm=TRUE),2),
           # cv = round((sqrt(exp(var.error)-1)),2),
            #icc = round(var.resid/(var.resid+var.error),2)
            max = max(Concentration,na.rm=TRUE),
         icc.new = round(  s2_between_subject/(s2_between_subject+s2_within_subject+s2_between_batch), 4)  ,
          cv.new = round(sqrt(s2_within_subject + s2_between_batch)/mean(Concentration,na.rm=TRUE),4)))


qc.stats = qc.stats.old %>% left_join(qc.stats.new,by="Estrogen") %>% select(Estrogen,icc.old,icc.new,cv.old,cv.new)

estrogen_max = qc.df %>% group_by(Estrogen) %>% summarise(max = max(Concentration,na.rm=TRUE)) 

 # filter(abs(log.sd.above.mean)>=2)
#write.xlsx(as.data.frame(qc_outliers),"C:/Users/zhaoi2/Desktop/qc_outliers.xlsx" , sheetName="Sheet1", col.names=TRUE, row.names=FALSE, showNA=FALSE)

                              
blank = data.frame(Estrogen = rep(estrogen_max$Estrogen,2), x=0,y=c(0-estrogen_max$max/15,estrogen_max$max + 2*estrogen_max$max)) %>% arrange(Estrogen)


ggplot(qc.df,aes(x=type.ID,y=Concentration)) +
  stat_boxplot(geom ='errorbar',alpha=0.5) + 
  geom_boxplot(color="grey60",outlier.shape = NA,alpha=0.25) +
  geom_jitter(aes(color=batch.num,shape=batch.num),size=3.5,alpha=0.6,width=0.3,height=0,show_guide = TRUE) +
  scale_shape_manual(values=1:nlevels(qc.df$batch.num))+
  theme_classic() +  
  geom_vline(data = data.frame(Estrogen= sort(rep(unique(qc.df$Estrogen),length(unique(qc.df$ID)))), id.num=rep(1:length(unique(qc.df$ID)),length(unique(qc.df$Estrogen)))),
             aes(xintercept=id.num),color="grey10",linetype="dotted")+
  scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  #scale_y_log10()+
  ylab("Estrogen metabolite concentration (pg) in 66.66 uL urine injection")+
  xlab("ID")+ 
  labs(color='Batch') +
  labs(shape='Batch') + 
  #geom_text_repel(data=subset(qc_outliers, abs(log.sd.above.mean)>=1.96), aes(x=ID,y=Concentration,label=customer.id))+
  #geom_text(data=qc.stats, aes(0.5,3*max,label=paste0("CV=",as.character(cv) )))+
  #geom_text(data=qc.stats, aes(0.5,1.75*max,label=paste0("ICC=",as.character(icc) )))+
 # geom_blank(data = blank, aes(x = x, y = y))+
  facet_wrap(~ Estrogen,scales="free",ncol=5) 
```

