```{r}
setwd("C:/Users/zhaoi2/Desktop/project") 
source("./Supplemental/check_packages.R")
source("./Supplemental/custom_cormatrix.R")  # use to load correlation matrix function
check_packages(c("optimx","metafor","stringr","Hmisc","ggpubr","readxl","xlsx","sas7bdat","readstata13","gridExtra","RColorBrewer","sjPlot",
                 "grid","lme4","ggrepel","tidyr","networkD3","dplyr","ggplot2"))

# Name estrogens
estrogen_names = c("E1", "E2", "4OHE1", "4ME1","4ME2","2OHE1","3ME1" ,"2OHE2","2ME1","2ME2","16aE1","17epiE3","E3","16KE2","16epiE3") 
estrogen_names_long = c("Estrone (E1)", "Estradiol (E2)", "4-Hydroxyestrone (4OHE1)", "4-Methoxyestrone (4ME1)","4-Methoxyestradiol (4ME2)","2-Hydroxyestrone (2OHE1)","2-Hydroxyestrone-3-methyl ether (3ME1)" ,"2-Hydroxyestradiol (2OHE2)","2-Methoxyestrone (2ME1)","2-Methoxyestradiol (2ME2)","16a-Hydroxyestrone (16aE1)","17-Epiestriol (17epiE3)","Estriol (E3)","16-Ketoestradiol (16KE2)","16-Epiestriol (16epiE3)")
estrogen_names_long2 = c("Estrone", "Estradiol", "4-Hydroxyestrone", "4-Methoxyestrone","4-Methoxyestradiol","2-Hydroxyestrone","2-Hydroxyestrone-3-methyl ether" ,"2-Hydroxyestradiol","2-Methoxyestrone","2-Methoxyestradiol","16a-Hydroxyestrone","17-Epiestriol","Estriol","16-Ketoestradiol","16-Epiestriol")
estrogen_names_df = data.frame(Estrogen = estrogen_names, Nomenclature = estrogen_names_long2)
t.estrogen_names = paste0("t.",estrogen_names)

load("./data/df_all.RDA")
```


```{r}
duplicates = df %>% group_by(customer.id) %>% filter(n() >1) %>% select(case, origin, age, bmi, alcohol, smoking, education, relativegc) %>% 
  group_by(case,origin  ) %>% filter(!is.na(case)) %>% arrange(customer.id)

unique = duplicates[seq(1,nrow(duplicates),by=2),   ]

char.df = df %>% group_by(customer.id) %>% filter(n() ==1) %>% select(case, origin, age, bmi, alcohol, smoking, education, relativegc) %>% 
  bind_rows(unique) %>%
  group_by(case,origin  ) %>% filter(!is.na(case))


means = char.df %>% summarize(n = n(), mean_age = mean(age,na.rm=TRUE), sd_age = sd(age,na.rm=TRUE), mean_bmi = mean(bmi,na.rm=TRUE), sd_bmi = sd(bmi,na.rm=TRUE) )
smoking = char.df %>% group_by(case,origin,smoking  ) %>% summarize(n=n())
alcohol = char.df  %>% group_by(case,origin,alcohol  ) %>% summarize(n=n())
education = char.df %>% group_by(case,origin,education ) %>% summarize(n=n())
relativegc = char.df %>%  group_by(case,origin,relativegc ) %>% summarize(n=n())
```

```{r}
replicate_ids = df %>% group_by(customer.id) %>% filter(n() >1)  %>% filter(!is.na(case)) %>% arrange(customer.id)
replicate_ids_copy = replicate_ids
#i=1
#replicate_ids[,which(colnames(replicate_ids)== estrogen_names[i])]
colnames(replicate_ids[,estrogen_names]) = paste0("_",estrogen_names)
  
  
  
)

df = df %>% group_by(customer.id) %>% filter(n() ==1) %>% 
  bind_rows(replicate_ids) %>% filter(!is.na(case))


means = char.df %>% summarize(n = n(), mean_age = mean(age,na.rm=TRUE), sd_age = sd(age,na.rm=TRUE), mean_bmi = mean(bmi,na.rm=TRUE), sd_bmi = sd(bmi,na.rm=TRUE) )
smoking = char.df %>% group_by(case,origin,smoking  ) %>% summarize(n=n())
alcohol = char.df  %>% group_by(case,origin,alcohol  ) %>% summarize(n=n())
education = char.df %>% group_by(case,origin,education ) %>% summarize(n=n())
relativegc = char.df %>%  group_by(case,origin,relativegc ) %>% summarize(n=n())
```

