


Correlation matrix of Estrogens signficantly associated with cancer, grouped by origin
```{r}
install.packages("GGally")
library(GGally)  # correlation matrix for groups
lower_plot <- function(data, mapping, method="lm", ...){     # custom points
      ggplot(data = data, mapping = mapping) + 
      geom_point(mapping = aes_string(color="origin",fill="origin"), alpha=0.2,size=1.5) + 
      geom_smooth(mapping = aes_string(color="origin"),method=method, se=FALSE,...)+
        scale_y_continuous(trans='log2') +
      scale_x_continuous(trans='log2') 
    }
diagonal_plot <- function(data, mapping, ...){       # density curve just line
  ggplot(data = data, mapping=mapping) +
    geom_density(mapping = aes_string(color="origin"), fill=NA,size=1) +
    scale_x_continuous(trans='log2') +
    geom_hline(yintercept=0,color="white",size=1)
}

df.cor1 = df %>% select(colnames(df.s), case, origin) %>%
  #df[,c(which(colnames(df)=="s.E1"):which(colnames(df)=='s.Total'), which(colnames(df)=="case"),which(colnames(df)=="origin") )] 
  mutate(case = as.numeric(case)-1)
names(df.cor1)[1:15] = estrogen_names
ggpairs(data=df.cor1,   columns = c("4ME2","17epiE3","16epiE3","case"), axisLabels = "none",legends=F,
        #legend = c(2,1) +
       mapping = ggplot2::aes(color = origin),
        upper = list(continuous = wrap('cor', method = "spearman",size=3, hjust=0.15, alignPercent=0.9)), 
        diag = list(continuous = diagonal_plot),
       lower = list(continuous = lower_plot)
       )+
      theme_base() 
```


Correlation matrix of all Estrogens 
```{r}
cols = brewer.pal(11, "RdBu")   # goes from red to white to blue
pal = colorRampPalette(cols)
cor_colors = data.frame(correlation = seq(-1,1,0.01), correlation_color = pal(201)[1:201])  # assigns a color for each r correlation value
cor_colors$correlation_color = as.character(cor_colors$correlation_color)

panel.cor <- function(x, y, digits=2, cex.cor)
{
  text.size = 1.5
  par(usr = c(0, 1, 0, 1))
  u <- par('usr') 
  names(u) <- c("xleft", "xright", "ybottom", "ytop")
  r <- cor(x, y,method="spearman",use="complete.obs")
  test <- cor.test(x,y)
  bgcolor = cor_colors[2+(-r+1)*100,2]    # converts correlation coefficient into a specific color
  do.call(rect, c(col = bgcolor, as.list(u))) # colors the correlation box
  
  if (test$p.value> 0.05){
    text(0.5,0.5,"Insignificant",cex=1.5)  # change cex value to change size of "Insignificant"
  } else{
  text(0.5, 0.75, paste("r=",round(r,2)),cex=2.5) # prints correlatoin coefficient. change cex value to change size of correlation coefficient r
  text(.5, .25, paste("p=",formatC(test$p.value, format = "e", digits = 1))   ,cex=2)  # prints p value in scientific notation format. change cex value to change size of p value p.
  abline(h = 0.5, lty = 2) # draws a line between correlation coefficient and p value
  }
  
}
panel.smooth<-function (x, y, col = "black", bg = NA, pch = 19, cex = 1.2, col.smooth = "blue", span = 2/3, iter = 3, ...) {
  points(x, y, pch = pch, col = col, bg = bg, cex = cex)
  ok <- is.finite(x) & is.finite(y)
  if (any(ok)) 
    lines(stats::lowess(x[ok], y[ok], f = span, iter = iter), lwd=2.5, 
          col = col.smooth, ...)
}
panel.hist <- function(x, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(usr[1:2], 0, 1.5) )
  h <- hist(x, plot = FALSE)
  breaks <- h$breaks; nB <- length(breaks)
  y <- h$counts; y <- y/max(y)
  rect(breaks[-nB], 0, breaks[-1], y, col="cyan", ...)
}


df.cor2 = df %>% select(colnames(df.s.log), case, origin) %>%
 # df[,c(which(colnames(df)=="log.s.E1"):which(colnames(df)=='log.s.Total'), which(colnames(df)=="case"),which(colnames(df)=="origin") )] %>%
  mutate(case = as.numeric(case)-1)
names(df.cor2)[1:15] = estrogen_names
pairs(df.cor2[1:16],lower.panel=panel.smooth, upper.panel=panel.cor,diag.panel=panel.hist,cex.labels=2)
```


Outlier detection
```{r}
outlier.df = df[,1:which(colnames(df)=="H_pylori")] %>% 
  gather(Estrogen,Concentration,7:21) %>% group_by(Estrogen) %>% 
  mutate(log.Concentration = log(Concentration),
    log.mean = mean(log.Concentration,na.rm=TRUE),
         log.median = median(log.Concentration,na.rm=TRUE),
         log.sd = sd(log.Concentration,na.rm=TRUE),
         log.sd.above.mean = round((log.Concentration-log.mean)/log.sd,2),
         pvalue = pnorm(log.Concentration, mean=log.mean, sd=log.sd,lower.tail=FALSE),
  mean = mean(Concentration,na.rm=TRUE),
  median = median(Concentration,na.rm=TRUE)) %>%
  filter(log.Concentration >= log.mean + 3*log.sd) %>%
  select(-study) %>%
  arrange(pvalue)
#write.xlsx(as.data.frame(outlier.df),"C:/Users/zhaoi2/Desktop/outliers.xlsx" , sheetName="Sheet1", col.names=TRUE, row.names=FALSE, showNA=FALSE)

outlier.plot = df %>% select(customer.id,estrogen_names) %>% 
  gather(Estrogen,Concentration,2:16) %>% 
  group_by(Estrogen) %>% 
  mutate(log.Concentration = log(Concentration),
    log.mean = mean(log.Concentration,na.rm=TRUE),
         log.sd = sd(log.Concentration,na.rm=TRUE),
         log.sd.above.mean = round((log.Concentration-log.mean)/log.sd,2),
         pvalue = pnorm(log.Concentration, mean=log.mean, sd=log.sd,lower.tail=FALSE))

 ggplot(outlier.plot,aes(x=customer.id,y=Concentration)) +
   geom_point(size=2,color="blue",alpha=0.6)+
   #geom_point(aes(color=abs(log.sd.above.mean)),size=2,alpha=0.9)+
   #scale_color_gradient2(low = "grey30",high = "red2")+
     theme_classic() +  
    ylab("Concentration (pmol/L)")+
   xlab("")+ 
     theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+  
   geom_text_repel(data=subset(outlier.plot, abs(log.sd.above.mean)>=3), aes(x=customer.id,y=Concentration,label=customer.id))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  facet_wrap(~ Estrogen,scales="free_y",ncol=5) 
```


QC analysis all
```{r}

qc.df.snu = df %>% filter(origin=="Korea (SNU)") %>% select(batch.num,customer.id,estrogen_names) %>% group_by(customer.id) %>% filter(n() >1) %>% filter(!(customer.id %in% c("0080","0121"))) %>% arrange(customer.id) %>% dplyr::rename(ID = customer.id) %>% mutate(batch.num=as.character(batch.num)) 
# remove"S1110234","S1210075"
names(qc.df.snu)[3:17] = estrogen_names_long
qc.df.snu = gather(qc.df.snu,Estrogen,Concentration,3:17)%>%
    mutate(batch.num = factor(as.factor(batch.num),levels = as.character(seq(1:16)))) 


 qc.df = as.data.frame(read_xlsx("./data/all_controls.xlsx",na="")) %>% 
  select(batch.num,ID,estrogen_names)
 names(qc.df)[3:17] = estrogen_names_long
 qc.df = qc.df %>%
   mutate(batch.num=as.character(batch.num)) %>%
  gather(Estrogen,Concentration,3:17) %>%
  bind_rows(qc.df.snu) %>%
  mutate(Estrogen = factor(as.factor(Estrogen),levels = estrogen_names_long),
  batch.num = factor(as.factor(batch.num),levels = as.character(seq(1:16))      ),
  ID=replace(ID, ID=='A', ' A'),
  ID=replace(ID, ID=='B', ' B'),
  ID=replace(ID, ID=='D', ' D'),
  ID=replace(ID, ID=='E', ' E')
  )

###############################################

 #qc.df = qc.df.snu

qc.stats = as.data.frame(qc.df %>% group_by(Estrogen) %>% 
  summarise(var.error =    round((attr(VarCorr(lmer(Concentration ~ 1+ (1|ID   ))), "sc"))^2,2),
          var.resid =   round(VarCorr(lmer(Concentration ~ 1+ (1|ID   )))$ID[1],2),
          cv = round(sqrt(var.resid)/mean(Concentration,na.rm=TRUE),2),
          icc = round(var.resid/(var.resid+var.error),2),
          max = max(Concentration,na.rm=TRUE) ))

#sjPlot::tab_df(qc.stats[,1:5],show.rownames=FALSE)



 estrogen_max = qc.df %>% group_by(Estrogen) %>% summarise(max = max(Concentration,na.rm=TRUE))
 plot.lines = df %>% select(estrogen_names) 
 names(plot.lines) = estrogen_names_long
 plot.lines = plot.lines %>% gather(Estrogen,Concentration,1:15) %>% group_by(Estrogen) %>% 
   summarise(median = median(Concentration,na.rm=TRUE), 
             Q10= as.numeric(quantile(Concentration,0.1,na.rm=TRUE)),  
             Q90= as.numeric(quantile(Concentration,0.9,na.rm=TRUE)),
             Q25 = as.numeric(quantile(Concentration,0.25,na.rm=TRUE)), 
             Q75 = as.numeric(quantile(Concentration,0.75,na.rm=TRUE)), 
             IQR = as.numeric(IQR(Concentration,na.rm=TRUE))) %>%
   inner_join(estrogen_max,by="Estrogen") %>%
    mutate(Estrogen = factor(as.factor(Estrogen),levels = estrogen_names_long))
blank = data.frame(Estrogen = rep(plot.lines$Estrogen,2), x=0,y=c(0-plot.lines$max/15,plot.lines$max + 2*plot.lines$max)) %>% arrange(Estrogen)
 
 
 ggplot(qc.df,aes(x=ID,y=Concentration)) +
   stat_boxplot(data = subset(qc.df,ID %in% c(" A" , " B"," D"," E")) ,geom ='errorbar',alpha=0.5) + 
   geom_boxplot(data=subset(qc.df,ID %in% c(" A" , " B"," D"," E")),color="grey60",outlier.shape = NA,alpha=0.25) +
   geom_jitter(aes(color=batch.num,shape=batch.num),size=3.5,alpha=0.5,width=0.3,height=0,show_guide = TRUE) +
   scale_shape_manual(values=1:nlevels(qc.df$batch.num))+
   theme_classic() +  
   geom_hline(data=plot.lines, aes(yintercept=median,linetype="Median"),color="green1")+
   geom_hline(data=plot.lines, aes(yintercept=Q10,linetype="Interdecile Range"),color="blue1")+
  geom_hline(data=plot.lines, aes(yintercept=Q90,linetype="Interdecile Range"),color="blue1" )+
   geom_hline(data=plot.lines, aes(yintercept=Q75+1.5*IQR,linetype="Outlier Boundary"),color="red2")+
    scale_linetype_manual(name = "Statistic", values = c(2,2,2), guide = guide_legend(override.aes = list(color = c("blue1","green1","red2"))))+
   geom_vline(data = data.frame(Estrogen= sort(rep(unique(qc.df$Estrogen),length(unique(qc.df$ID)))), id.num=rep(1:length(unique(qc.df$ID)),length(unique(qc.df$Estrogen)))),
              aes(xintercept=id.num),color="grey10",linetype="dotted")+
  scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x))) +
 ylab("Concentration (pmol/L)")+
   xlab("ID")+ 
     theme(axis.text.x = element_text(angle = 60, hjust = 1))+
   labs(color='Batch') +
   labs(shape='Batch') + 
   geom_text(data=qc.stats, aes(2,3*max,label=paste0("CV=",as.character(cv) )))+
     geom_text(data=qc.stats, aes(2,1.75*max,label=paste0("ICC=",as.character(icc) )))+
   geom_blank(data = blank, aes(x = x, y = y))+
   facet_wrap(~ Estrogen,scales="free_y",ncol=5) 


```



Compare countries
```{r}
e = df %>% select(colnames(df.s), creatinine, origin) %>%
 filter(origin %in% c("Germany", "Japan", "Korea (KMCC)", "Iran")) 
colnames(e)[1:15] = estrogen_names_long
f = gather(e, Estrogen, Concentration, 1:15) %>% mutate(Estrogen = factor(as.factor(Estrogen),levels = c(estrogen_names_long,"creatinine")) )

#my_comparisons <- list( c("Germany", "Japan"), c("Germany", "Korea (KMCC)"), c("Japan", "Korea (KMCC)"))

ggplot(data = f, aes(x=origin,y=Concentration, fill=origin)) +
  geom_boxplot(color="black",alpha=0.7) +
    stat_summary(fun.y = mean, geom = "point", shape = 18, size = 4, color = "black")+
  theme_classic()+
  #stat_compare_means(comparisons = my_comparisons)+
  scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
              labels = scales::trans_format("log10", scales::math_format(10^.x))) +
facet_wrap(~ Estrogen, scales="free",ncol=5) +
  theme(legend.position="none")+
  xlab("")+
  ylab("")
```

forestplot
```{r}
# get forest plot of age + bmi
df.coef1 = data.frame(estrogen = c("Estrogen",estrogen_names_long2),beta=rep(NA,16), lower = rep(NA,16), upper = rep(NA,16))

for (i in 1:15){
model = summary(glm(as.formula(paste0("case", " ~ ", (paste(t.estrogen_names[i], "age", sep="+")))), data=df,  family=binomial(link="logit")))$coef
df.coef1$beta[i+1] = exp(model[2,1])
df.coef1$lower[i+1] = exp(model[2,1]-1.96*model[2,2])
df.coef1$upper[i+1] = exp(model[2,1]+1.96*model[2,2])
}
df.coef1$estrogen = as.character(df.coef1$estrogen)

tabletext<-cbind(
df.coef1$estrogen,c("OR", round(df.coef1$beta[2:16],2)))

forestplot(tabletext,
          df.coef1[,2:4], 
          hrzl_lines = gpar(col="#444444"),
           is.summary=c(TRUE,rep(FALSE,15)),
           #clip=c(min(df.coef1$lower,na.rm=TRUE),max(df.coef1$upper,na.rm=TRUE)), 
          xlog=TRUE,
          boxsize=0.25,
          vertices = TRUE,
           col=fpColors(box="black",line="black", summary="black"))
```



```{r}
custom_graph1 <-function(indata, inx) {
    
    which(colnames(df)=="16KE2.s")
  
    colnames(df)
    indata = df
    inx = 8
    
    # dataframe of only Estrogen column #, status, and origin
    data = na.omit(data.frame(Estrogen=indata[,inx], 
                              Status=indata[,"study.status"], 
                              Status.overall = indata[,"case.name"],
                              Origin=indata[,"origin"]))  
    
    data$Status <- factor(data$Status, levels = c("Cohort - Case","C-C* - Case","Cohort - Control", "C-C* - Control"))
    
    data.stats = as.data.frame(data %>% dplyr::group_by(Status) %>% dplyr::summarise(Mean = mean(Estrogen), SD = sd(Estrogen)))
    data.stats2 = as.data.frame(data %>% dplyr::group_by(Status.overall) %>% dplyr::summarise(Mean2 = mean(Estrogen), SD = sd(Estrogen)))
    
    # mean and sd for status
    
    
    my_comparisons <- list( c("Cohort - Case", "Cohort - Control"), c("C-C* - Case", "C-C* - Control"))
    
    ############  Main plot   ########################################
    mainplot = ggplot(data,aes(x=Status,y=Estrogen)) +
    geom_violin(aes(fill=Status), trim = FALSE,alpha=0.5,color="black") +  # adds distribution grey60
    scale_fill_manual(values = c("coral1","coral3","deepskyblue1","deepskyblue3")) +  
    guides(fill=FALSE) +   # takes out legend for status
    geom_point(data=data.stats,aes(x=Status,y=Mean),size=20,color=c("red","red","blue","blue"),alpha=0.4,shape=42) +
    geom_boxplot(aes(color = Origin), width = 0.15,position = position_dodge(0.4),alpha=0.9) +
    scale_colour_manual(values = c("darkorange1","chartreuse4","gold3","plum4","hotpink")) +
    #geom_errorbar(data=data.stats,aes(x=Status,y=NULL,ymin = Mean-SD, ymax = Mean+SD), width = 0.05)+  
    theme_classic() +
    theme(axis.title = element_text(face="italic"))  +
      theme(legend.position="left") +
      xlab("")+
      ylab("Estrogen (pg) Standardized with Creatinine (mg/dL)")  +
    ggtitle("16KE2") +
    geom_vline(aes(xintercept=2.5),linetype="dotted") +
      stat_compare_means(comparisons = my_comparisons) 
      
    
    ################## Density side plot #############################
      ydensity = ggplot(data, aes(x=Estrogen)) + 
      geom_density(aes(fill=Status.overall,color=Status.overall), alpha=.3,size=1) + 
         scale_colour_manual(values = c("coral3","skyblue3"))+
      theme_classic() +
      theme(legend.position = "none",axis.line=element_blank(),
           #axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks = element_blank()) +
      xlab("") +
      ylab("") +
      geom_vline(aes(xintercept = data.stats2[data.stats2$Status.overall=="Case","Mean2"]), linetype = "dashed",color="coral3",size=0.75,alpha=0.6) +
      geom_vline(aes(xintercept = data.stats2[data.stats2$Status.overall=="Control","Mean2"]), linetype = "dashed",color="deepskyblue3",size=0.75,alpha=0.6) +
      xlim(0,max(data$Estrogen)*1.2)+
      coord_flip() +
        annotate("text", x = Inf, y = -Inf,  
          label = paste("p =",as.character(round(wilcox.test(Estrogen ~ Status.overall, data=data, alternative = "two.sided")$p.value,2)))   ,  hjust = -0.25, vjust = 1) 
      
      
      grid.arrange(mainplot, ydensity, ncol=2  , widths=c(6, 0.75)) 
  
      #1070 max(data[,"Estrogen"])
      
    
    # summary stats
    group_by(data, Status.overall) %>%
  summarise(
    count = n(),
    median = median(Estrogen, na.rm = TRUE),
    mean = mean(Estrogen,na.rm=TRUE),
    IQR = IQR(Estrogen, na.rm = TRUE)
  )

}
```