```{r}
setwd("C:/Users/zhaoi2/Desktop/project") 
source("./Supplemental/check_packages.R")
source("./Supplemental/custom_cormatrix.R")  # use to load correlation matrix function
check_packages(c("optimx","metafor","stringr","Hmisc","ggpubr","readxl","xlsx","sas7bdat","readstata13","gridExtra","RColorBrewer","sjPlot",
                 "grid","lme4","ggrepel","tidyr","networkD3","dplyr","ggplot2"))

# Name estrogens
estrogen_names = c("E1", "E2", "4OHE1", "4ME1","4ME2","2OHE1","3ME1" ,"2OHE2","2ME1","2ME2","16aE1","17epiE3","E3","16KE2","16epiE3") 
estrogen_names_long = c("Estrone (E1)", "Estradiol (E2)", "4-Hydroxyestrone (4OHE1)", "4-Methoxyestrone (4ME1)","4-Methoxyestradiol (4ME2)","2-Hydroxyestrone (2OHE1)","2-Hydroxyestrone-3-methyl ether (3ME1)" ,"2-Hydroxyestradiol (2OHE2)","2-Methoxyestrone (2ME1)","2-Methoxyestradiol (2ME2)","16a-Hydroxyestrone (16aE1)","17-Epiestriol (17epiE3)","Estriol (E3)","16-Ketoestradiol (16KE2)","16-Epiestriol (16epiE3)")
estrogen_names_long2 = c("Estrone", "Estradiol", "4-Hydroxyestrone", "4-Methoxyestrone","4-Methoxyestradiol","2-Hydroxyestrone","2-Hydroxyestrone-3-methyl ether" ,"2-Hydroxyestradiol","2-Methoxyestrone","2-Methoxyestradiol","16a-Hydroxyestrone","17-Epiestriol","Estriol","16-Ketoestradiol","16-Epiestriol")
estrogen_names_df = data.frame(Estrogen = estrogen_names, Nomenclature = estrogen_names_long2)
t.estrogen_names = paste0("t.",estrogen_names)

load("./data/df_all.RDA")
```


Get CV and ICC
```{r}
df.creatinine.list = list()  # will store all creatinine batches into one list of multiple dataframes
for (i in 1:6){  # reads in creatinine batches 1-5
  df.creatinine.list[[i]] = as.data.frame(read_xlsx(paste0("./data/Creatinine_Batch",as.character(i), ".xlsx"), na="QNS", skip=1))
  df.creatinine.list[[i]]$batch.num = i  # assigns batch number
  colnames(df.creatinine.list[[i]])[1:4] = c("sample.id","customer.id","#","creatinine")   # renames first 4 columns to standardize format
  df.creatinine.list[[i]]$sample.id = as.character(df.creatinine.list[[i]]$sample.id)  # Makes sample id a character type
  df.creatinine.list[[i]] = df.creatinine.list[[i]] %>% dplyr::select(-'#')  %>% # Removes # column
    mutate(creatinine = as.numeric(ifelse(creatinine=="<2.0",1, creatinine)))  # change <2.0 to 1
}

df.creatinine.list[[3]]$customer.id[11] = "0082"   # changes customer id from 0080 to 0082 for creatinine batch 3
df.creatinine.list[[4]]$creatinine = as.numeric(df.creatinine.list[[4]]$creatinine   )  # Makes creatinine numeric for batch 4
df.creatinine.list[[4]]$creatinine[c(30,31)] = c(43.3,81.6) # Enter linear regression prediction from japan creatinine for these lab error values
df.creatinine.list[[4]]$customer.id[37:40] = c("control_13","control_14","control_15","control_16")
df.creatinine.list[[6]]$customer.id[df.creatinine.list[[6]]$customer.id %in% c("C-21","C-22","C-23","C-24")] = c("C_21","C_22","C_23","C_24") # Relabels control customer ids in batch 6
df.creatinine = bind_rows(df.creatinine.list) %>% dplyr::select(batch.num,sample.id,customer.id,creatinine)  



qc.df = df.creatinine %>% filter(str_detect(customer.id, regex("control|C-|C_|Xia",ignore_case=TRUE))) %>%
  mutate(batch.num = as.factor(batch.num), ID = c("A","D","A","D","B","B","D","D","E","B","B","E","D","E","E","D","E","E","B","B","B","D","B","D")   ) %>%
  rename(Concentration = creatinine)

qc.stats = qc.df %>%
  mutate(ID = as.factor(ID)) %>% 
  #mutate(ID = as.factor(ID), Concentration = log(Concentration+1)) %>% 
  summarize(s2_between_subject = VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num)))$ID[1],           # between subject variance
            s2_between_batch = VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num)))$batch.num[1] ,          # between batch variance
            s2_within_subject = (attr(VarCorr(lmer(Concentration ~ 1+ (1|ID) + (1|batch.num))), "sc"))^2 ,    # within subject variance
            mean_concentration = mean(Concentration,na.rm=TRUE)) %>%
  mutate( icc = round(  100*(s2_between_subject/(s2_between_subject+s2_within_subject+s2_between_batch)), 1) ,
          cv = round( 100*(sqrt(s2_within_subject + s2_between_batch)/mean_concentration),1))

sjPlot::tab_df(qc.stats %>% mutate(s2_between_subject = round(s2_between_subject,2),
                                s2_between_batch = round(s2_between_batch,2),
                                s2_within_subject = round(s2_within_subject,2),
                                mean_concentration = round(mean_concentration,2)) ,show.rownames=FALSE)


ggplot(qc.df,aes(x=ID,y=Concentration)) +
  #stat_boxplot(geom ='errorbar',alpha=0.2) + 
  #geom_boxplot(color="grey90",outlier.shape = NA,alpha=0.2) +
  geom_jitter(aes(color=batch.num,shape=batch.num),size=7.5,width=0.2,height=0,show_guide = TRUE) +
  scale_shape_manual(values=1:nlevels(qc.df$batch.num))+
  theme_classic() +  
  geom_vline(data = data.frame(ID = c(1,2,3,4)), aes(xintercept=ID), color="grey50",linetype="dotted",size=1.5)+
  #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  ylab("Creatinine (mg/dL)")+
  xlab("QC ID") + 
  labs(color='Batch') +
  labs(shape='Batch') +
  scale_y_continuous(breaks=seq(0,200,10))+
  geom_label(data=qc.stats, aes(4,170,label=paste0("CV=",as.character(cv),"%","\n","ICC=",as.character(icc),"%"  )), fontface = "bold",size=7)+
     theme(axis.title = element_text(size=15, face="bold"), axis.text.y =  element_text(size=15,face="bold"),
          axis.text.x =  element_text(size=15,face="bold")     )
  #geom_text(data=qc.stats, aes(0.5,3*max,label=paste0("CV=",as.character(cv) )))+
  #geom_text(data=qc.stats, aes(0.5,1.75*max,label=paste0("ICC=",as.character(icc) )))+
  #geom_blank(data = blank, aes(x = x, y = y))+

```


Relationship of creatinine to estrogens
```{r}
a = df %>% select(estrogen_names,creatinine,batch.num,customer.id) %>%  gather(Estrogen,Concentration,estrogen_names) %>% mutate(batch.num=as.factor(batch.num)) %>%
  filter(customer.id != "1055")
ggplot(a,aes(x=creatinine,y=Concentration)) +
  geom_point(color="steelblue3",size=2,alpha=0.5,show_guide = TRUE) +
  theme_classic()+
  scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  ylab("Creatinine (mg/L)")+
  geom_smooth(method="lm",color="coral2",size=2,se=FALSE)+
  xlab("Estrogen Concentration (pmol/L)") + 
  facet_wrap(~ Estrogen,scales="free",ncol=5)+
  ggtitle("Relationship between Creatinine and Estrogen Concentrations")+
  stat_cor(method = "pearson", label.x = 3500, label.y.npc="top")


```







